# Generated by Django 3.2.9 on 2021-11-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=19, unique=True)),
                ('mbti', models.CharField(blank=True, max_length=4)),
                ('gender', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
