# Generated by Django 3.2.9 on 2021-11-25 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='INVALID_EMAIL')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(error_messages={'max_length': 'NAME_TOO_LONG'}, max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='INVALID_NAME')]),
        ),
    ]
