# Generated by Django 3.2.9 on 2021-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211128_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='followed', through='users.Follow', to='users.User'),
        ),
    ]
