# Generated by Django 3.2.9 on 2021-11-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_bf',
        ),
    ]
